# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a7345f6d829791c505216ea3fdbfc5bc9aded0cf5ae5f9d70d225be435d095e12958118ed0fbfbc6edc00734d612b8c9088cb0fb80a5bc7c49d174b932ffa2b

test:
  secret_key_base: 7dbdca0a0dbf3524eb3e84cb590d8b4902da81922de03fdfeddf13ce5e87140cf527ef0b2896eeed2e2626423e14868cd970d934abe6544b460f6b6899293f62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
